# Generated by Django 5.1 on 2024-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=80)),
                ('model', models.CharField(default='', max_length=80)),
                ('year', models.CharField(default='', max_length=4)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
